{ ... }:
{
  wayland.windowManager.hyprland = {
    enable = true;
    settings = {
      monitor = "DP-1,1920x1080@179.98,0x0,1.25";
      "$mainMod" = "SUPER";
      "$menu" = "wofi --show drun -G -I -i";
      "$terminal" = "kitty";

      autogenerated = 0;

      bind = [
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, up, movefocus, u"
        "$mainMod, down, movefocus, d"
        "$mainMod, left, movefocus, l"
        "$mainMod, right, movefocus, r"
        "$mainMod, C, killactive"
        "$mainMod, J, togglesplit,"
        "$mainMod, R, exec, $menu"
        "$mainMod, T, exec, $terminal"
        "$mainMod, M, exit"
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
      ];

      decoration = {
        active_opacity = 1.0;
        inactive_opacity = 0.5;

        rounding = 15;
        rounding_power = 3;
      };

      input = {
        kb_layout = "tr";
        sensitivity = -1.5;
      };

      misc = {
        force_default_wallpaper = 1;
      };
    };
    xwayland.enable = true;
  };
}
